ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      chaitnya.dev.SerializationKt.configureSerialization
      chaitnya.dev.PostgresKt.configurePostgres
      chaitnya.dev.ExposedKt.configureExposed
      chaitnya.dev.RoutingKt.configureRouting
    ]
  }
}